apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongo-pod
      namespace: chat-app
      labels:
        app: mongodb
    spec:
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: chatapp-mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: secret
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
